### ISSUE TITLE
Document locations backfill issue

### ISSUE THREAD

**Issue by gwionap** [moj-analytical-services/airflow-matrix-scraper#54]
Add information on lack of ability to backfill locations because of API design in repo README

**Comment by williamorrie** [comment]
Readme updated.

Should the pipeline be amended to prevent the possibility of historical locations data being overwritten?

**Comment by williamorrie** [comment]
#55 covers the above query

**Comment by williamorrie** [comment]
Further explaination of how this problem was discovered is documented in #56
