### ISSUE TITLE
Promote historic dev locations data to prod

### ISSUE THREAD

**Issue by gwionap** [moj-analytical-services/airflow-matrix-scraper#56]
- Solves lack of historic data in prod

**Comment by williamorrie** [comment]
This relates to #54 

`matrix_dev.locations` has an earliest consistent location count (approx. 4900) from an ingestion date of `2024-03-25`, location data from earlier ingestions have a much smaller count, suggesting that the extraction code prior to this was incorrect. 
`matrix_prod.locations` has an earliest consistent location count (approx. 5215) from an ingestion date of `2024-04-30`

Laurence Droy has asked that prod data be updated with the dev data as there is an extra month of historical data

**Comment by williamorrie** [comment]
PR - https://github.com/moj-analytical-services/airflow-matrix-scraper/pull/57
